version: "3.7"
#Based on https://github.com/akeneo/pim-community-dev/blob/master/docker-compose.yml

services:
  fpm:
    build:
      dockerfile: ./build/fpm.Dockerfile
      context: .
    environment:
      APP_ENV: '${APP_ENV:-prod}'
      COMPOSER_HOME: '/var/www/.composer'
    volumes:
      - './app:/srv/app'
      - '${HOST_COMPOSER_HOME:-~/.composer}:/var/www/.composer'
      - './config/php/php.ini:/usr/local/etc/php/php.ini:ro'
    working_dir: '/srv/app'
    command: 'php-fpm -F'
    init: true
    networks:
      - 'app'

  httpd:
    image: 'httpd:2.4'
    environment:
      APP_ENV: '${APP_ENV:-prod}'
    depends_on:
      - 'fpm'
    ports:
      - '${PORT_HTTP:-80}:80'
    volumes:
      - './app:/srv/app:ro'
      - './config/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro'
      - './config/apache/vhost.conf:/usr/local/apache2/conf/vhost.conf:ro'
    networks:
      - 'app'

  mysql:
    image: 'mysql:8.0.22'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: '${APP_DATABASE_USER:-test_user}'
      MYSQL_DATABASE: '${APP_DATABASE_NAME:-test_db}'
      MYSQL_PASSWORD: '${APP_DATABASE_PASSWORD:-test_pass}'
    volumes:
      - './config/mysql/initdb.d:/docker-entrypoint-initdb.d:ro'
    ports:
      - '${APP_PORT_MYSQL:-33006}:3306'
    networks:
      - 'app'

networks:
  app: